//AUTH
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_ERRORS_LOGIN = 'SET_ERRORS_LOGIN';
export const SET_ERRORS_REGISTER = 'SET_ERRORS_REGISTER';
export const UNSET_ERRORS = 'UNSET_ERRORS';

//USER
export const SET_USER_DETAILS_LOADING = 'SET_USERS_DETAILS_LOADING';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const SET_GET_USERS_LOADING = 'SET_GET_USERS_LOADING';
export const GET_USERS = 'GET_USERS';
export const RESET_USER_DETAILS = 'RESET_USER_DETAILS';

//POSTS
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const SET_POSTS_LOADING = 'SET_POSTS_LOADING';
export const SET_POST_IS_EDIT = 'SET_POST_IS_EDIT';
export const SET_POST_COMMENT_IS_EDIT = 'SET_POST_COMMENT_IS_EDIT';
export const RESET_POSTS = 'RESET_POSTS';
export const RESET_POST = 'RESET_POST';

//NOTIFICATIONS
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS'
export const SET_NOTIFICATIONS_LOADING = 'SET_NOTIFICATIONS_LOADING';

//MESSAGES
export const GET_MESSAGES = 'GET_MESSAGES';
export const SET_MESSAGES_LOADING = 'SET_MESSAGES_LOADING';
export const CLEAR_MESSAGES_LOADING = 'CLEAR_MESSAGES_LOADING';
export const RESET_MESSAGES = 'RESET_MESSAGES'
