//AUTH
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_ERRORS_LOGIN = 'SET_ERRORS_LOGIN';
export const SET_ERRORS_REGISTER = 'SET_ERRORS_REGISTER';
export const UNSET_ERRORS = 'UNSET_ERRORS';

//USER
export const GET_USER_DETAILS = 'GET_USER_DETAILS';

//POSTS
export const GET_POSTS = 'GET_POSTS';
export const SET_POSTS_LOADING = 'SET_POSTS_LOADING';
export const SET_POST_IS_EDIT = 'SET_POST_IS_EDIT';
export const SET_POST_COMMENT_IS_EDIT = 'SET_POST_COMMENT_IS_EDIT';
